"Print 1D array with 5 zeros."

In [2]:
import numpy as np

array_with_5_zeros = np.zeros(5)
print(array_with_5_zeros)


[0. 0. 0. 0. 0.]


"Print Range Between 1 To 15 and show 4 integers random numbers"

In [3]:
import numpy as np

# Printing the range between 1 to 15
print(np.arange(1,16))

# Showing 4 random integers
print(np.random.randint(0, 100, 4))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[88 99 88 86]


"Print the odd number from arrange of 1 to 99 using arange function."

In [4]:
import numpy as np

odd_numbers = np.arange(1, 100, 2)
print(odd_numbers)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


"Print the numpy version and the configuration"

In [5]:
import numpy as np

print("NumPy version:", np.__version__)
np.show_config()


NumPy version: 1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/LENOVO/anaconda3\\Library\\include']
Supported SIMD extensi

"How to get the positions where elements of two arrays match?"

In [6]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 4, 6, 8, 10])

matching_positions = np.where(array1 == array2)

print(matching_positions)


(array([], dtype=int64),)


"Write a NumPy program to test element-wise for NaN of a given array."

In [7]:
import numpy as np

arr = np.array([1, 2, np.nan, 4, 5])
print(np.isnan(arr))


[False False  True False False]


"What is negative indexing in a NumPy array"

Negative indexing in a NumPy array refers to accessing elements in the array by counting from the end of the array, rather than from the beginning. 

"What is numpy.zeros()? Explain with example"

numpy.zeros() is a function in the NumPy library that creates a new array of specified size and fills it with zeros.

In [8]:
import numpy as np

# Creating a 1D array with 5 zeros
a = np.zeros(5)
print(a)


[0. 0. 0. 0. 0.]


"Create a 3x3x3 array with random values"

In [9]:
import numpy as np

array = np.random.rand(3, 3, 3)
print(array)


[[[0.65843431 0.68290287 0.63973427]
  [0.17930213 0.93474876 0.83745702]
  [0.96668328 0.18368663 0.30917321]]

 [[0.78789019 0.88331516 0.07933934]
  [0.31296114 0.96291576 0.9050814 ]
  [0.65364379 0.20765345 0.26601528]]

 [[0.75537649 0.01979038 0.40985099]
  [0.21990486 0.7607352  0.30341625]
  [0.97883988 0.41241283 0.23365681]]]


"Normalize a 5x5 random matrix"

In [10]:
import numpy as np

# Create a 5x5 random matrix
matrix = np.random.rand(5, 5)

# Normalize the matrix by subtracting the mean and dividing by the standard deviation
normalized_matrix = (matrix - matrix.mean()) / matrix.std()

print("Original matrix:\n", matrix)
print("Normalized matrix:\n", normalized_matrix)


Original matrix:
 [[0.8291971  0.38596598 0.78799971 0.59577002 0.38275257]
 [0.4019394  0.49469353 0.08457566 0.79729774 0.33264215]
 [0.31430629 0.39493949 0.50716926 0.94748661 0.89330696]
 [0.37632428 0.47376898 0.65098105 0.44745453 0.29734229]
 [0.24446482 0.67958618 0.87382965 0.2605723  0.88171724]]
Normalized matrix:
 [[ 1.24037026 -0.61850964  1.06759132  0.26139363 -0.63198646]
 [-0.55151823 -0.16251399 -1.88251928  1.10658659 -0.84214601]
 [-0.9190453  -0.58087537 -0.11019167  1.73646808  1.50924244]
 [-0.65894624 -0.25027009  0.49294476 -0.36063101 -0.9901911 ]
 [-1.21195548  0.61291264  1.42755599 -1.14440186  1.460636  ]]


"Why is NumPy used in Python?"

NumPy is used in Python for scientific computing and data analysis. The main reason for its widespread usage is because it provides a high-performance multi-dimensional array object, called ndarray, that allows to store and manipulate large arrays of homogeneous data (i.e., elements of the same type). 

"Create a 10 x 10 array of zeros and then "frame" it with a border of ones."

In [11]:
import numpy as np

# Create a 10x10 array of zeros
array = np.zeros((10, 10))

# Create a border of ones around the array
array[0,:] = 1
array[:,0] = 1
array[-1,:] = 1
array[:,-1] = 1

print(array)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


"How to get the diagonal of a dot product?"

The diagonal of a dot product is simply the product of the diagonal elements of the two matrices being multiplied.

In [13]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

diag_A = np.diag(A)
diag_B = np.diag(B)

dot_product = np.dot(diag_A, diag_B)
dot_product 

242

"What is numpy.zeros()? Explain with example"

numpy.zeros() is a function in the NumPy library for Python that creates a new array of specified size and type, filled with zeros.

In [14]:
import numpy as np

# Create a 3x4 array filled with zeros
a = np.zeros((3, 4), dtype=int)
print(a)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


"Create a random number of size 10 and find the mean value"

In [15]:
import numpy as np

# Create a random number of size 10
a = np.random.rand(10)
print(a)

# Find the mean value
mean_value = np.mean(a)
print(mean_value)


[0.27342613 0.52276187 0.55734207 0.37949476 0.15429099 0.75286313
 0.0010496  0.56419726 0.88183915 0.86017766]
0.49474426306429564
