In [1]:
import numpy as np

In [2]:
%timeit (j**4 for j in range(1,9))

1.23 µs ± 35.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [3]:
l=[1,3,5,4]
a=np.array(l)

In [4]:
print(a)

[1 3 5 4]


In [5]:
l=[]
for i in range(1,5):
    int_l=int(input('enter number'))
    l.append(int_l)
print(np.array(l))


enter number1
enter number2
enter number3
enter number4
[1 2 3 4]


In [7]:
ar=np.array([[1,24,5],[3,54,7]])
print(ar)
print(ar.ndim)

[[ 1 24  5]
 [ 3 54  7]]
2


In [9]:
arr=np.array(l,ndmin=7)
print(arr)
print(arr.ndim)

[[[[[[[1 2 3 4]]]]]]]
7


In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
ar_em=np.empty(4)

In [16]:
ar_em

array([0., 0., 0., 0.])

In [17]:
np.empty((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.arange(4)

array([0, 1, 2, 3])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [26]:
np.linspace(1,19,num=8)

array([ 1.        ,  3.57142857,  6.14285714,  8.71428571, 11.28571429,
       13.85714286, 16.42857143, 19.        ])

In [27]:
np.random.rand(4)

array([0.17459859, 0.39514125, 0.60006594, 0.44950618])

In [29]:
print(np.random.rand(4,5))

[[0.58339972 0.64956614 0.4970306  0.71476433 0.34856643]
 [0.94110326 0.45595878 0.71506398 0.22357232 0.41101864]
 [0.7447464  0.5286752  0.164666   0.34806818 0.83432526]
 [0.49843511 0.54520412 0.58407892 0.21583636 0.37833838]]


In [30]:
np.random.randn(5)

array([ 0.11874749, -0.865296  , -0.28009239,  1.25456484,  0.85822909])

In [31]:
np.random.randn(3,4)

array([[ 0.78329764,  0.22553876, -1.20954292,  0.02103802],
       [ 0.06485393,  0.44229953, -0.46020073, -0.71225035],
       [ 0.00896922,  1.25683429,  0.23782422,  0.08437912]])

In [33]:
np.random.ranf(3)

array([0.44568944, 0.15378866, 0.55135261])

In [35]:
np.random.ranf((3,3))

array([[0.7904414 , 0.29460997, 0.64058362],
       [0.55214163, 0.56339601, 0.33326077],
       [0.71704664, 0.58242834, 0.22526541]])

In [39]:
np.random.randint(3,34,5)

array([20, 21, 27,  6, 12])

In [40]:
np.random.randint(4,29,(3,3))

array([[25, 27, 17],
       [22, 10, 22],
       [15,  4, 20]])

In [41]:
var=np.array([2,3,45,5])
print(var.dtype)

int32


In [43]:
var=np.array(['3','d',3,4,44])
print(var.dtype)

<U11


In [45]:
a=np.array(['3','4'],dtype=np.int)
print(a.dtype)
print(a)


int32
[3 4]


C:\Users\HP\AppData\Local\Temp\ipykernel_12660\455313550.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.array(['3','4'],dtype=np.int)


In [46]:
x=np.array([1,4,46])
new=x.astype(float)
print(x)
print(new)

[ 1  4 46]
[ 1.  4. 46.]


In [49]:
a=np.array([1,3,45,6])
b=np.array([3,4,6,63])
np.add(a,b)

array([ 4,  7, 51, 69])

In [50]:
np.divide(a,b)

array([0.33333333, 0.75      , 7.5       , 0.0952381 ])

In [52]:
np.mod(a,b)

array([1, 3, 3, 6], dtype=int32)

In [53]:
np.subtract(a,b)

array([ -2,  -1,  39, -57])

In [54]:
np.multiply(a,b)

array([  3,  12, 270, 378])

In [56]:
np.power(a,b)

array([         1,         81, -286168967,          0], dtype=int32)

In [58]:
np.reciprocal(a,dtype='float')

array([1.        , 0.33333333, 0.02222222, 0.16666667])

In [68]:
print(a)

[ 1  3 45  6]


In [59]:
np.min(a)

1

In [60]:
np.max(a)

45

In [66]:
np.argmin(a)

0

In [67]:
np.argmax(a)

2

In [61]:
np.sqrt(a)

array([1.        , 1.73205081, 6.70820393, 2.44948974])

In [62]:
np.sin(a)

array([ 0.84147098,  0.14112001,  0.85090352, -0.2794155 ])

In [63]:
np.cos(a)

array([ 0.54030231, -0.9899925 ,  0.52532199,  0.96017029])

In [64]:
np.cumsum(a)

array([ 1,  4, 49, 55], dtype=int32)

In [72]:
var=np.array([a,b],ndmin=2)
print(np.min(var,axis=0))## 0  means column

[1 3 6 6]


In [74]:
print(var)

[[ 1  3 45  6]
 [ 3  4  6 63]]


In [75]:
print(var.shape)

(2, 4)


In [76]:
var1=np.array([2,4,6,3],ndmin=4)
print(var1)
print(var1.shape)

[[[[2 4 6 3]]]]
(1, 1, 1, 4)


In [92]:
var11=np.array([3,4,45,33,32])
x=var11.reshape((5,1))
print(x)

[[ 3]
 [ 4]
 [45]
 [33]
 [32]]


In [86]:
print(x.shape)
print(x.ndim)
print(var11.ndim)

(5, 1)
2
1


In [93]:
print(var11+x)

[[ 6  7 48 36 35]
 [ 7  8 49 37 36]
 [48 49 90 78 77]
 [36 37 78 66 65]
 [35 36 77 65 64]]


In [94]:
var=np.array([9,3,22,5])
print(var)
print(var[-1])

[ 9  3 22  5]
5


In [97]:
varr=np.array([a,b])
print(varr)
print(varr[0,3])

[[ 1  3 45  6]
 [ 3  4  6 63]]
6


In [98]:
print(varr[:,:2])

[[1 3]
 [3 4]]


In [99]:
for i in var:
    print(i)

9
3
22
5


In [100]:
print(varr)
for i in varr:
    for j in i:
        print(j)

[[ 1  3 45  6]
 [ 3  4  6 63]]
1
3
45
6
3
4
6
63


In [102]:
varr1=np.array((a,b),ndmin=3)

In [103]:
for i in varr1:
    for j in i:
        for k in j:
            print(k)

1
3
45
6
3
4
6
63


In [104]:
for i,d in np.ndenumerate(varr1):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 3
(0, 0, 2) 45
(0, 0, 3) 6
(0, 1, 0) 3
(0, 1, 1) 4
(0, 1, 2) 6
(0, 1, 3) 63


In [107]:
for i in np.nditer(varr):
    print(i)

1
3
45
6
3
4
6
63


In [108]:
var2=var1.copy()

In [109]:
print('arr:',var1)
print('copy:',var2)

arr: [[[[2 4 6 3]]]]
copy: [[[[2 4 6 3]]]]


In [110]:
var2.view()

array([[[[2, 4, 6, 3]]]])

In [117]:
var=np.array(a)
var1=np.array(b)
ar=np.concatenate((var,var1),axis=0)
print(ar)

[ 1  3 45  6  3  4  6 63]


In [122]:
print(np.stack((var,var1)))

[[ 1  3 45  6]
 [ 3  4  6 63]]


In [121]:
print(np.vstack((var,var1)))
print(np.hstack((var,var1)))
print(np.dstack((var,var1)))


[[ 1  3 45  6]
 [ 3  4  6 63]]
[ 1  3 45  6  3  4  6 63]
[[[ 1  3]
  [ 3  4]
  [45  6]
  [ 6 63]]]


In [131]:
ass=np.array_split(var,2,axis=0)

In [132]:
ass[0]

array([1, 3])

In [133]:
ass[1]

array([45,  6])

In [169]:
variable=np.array([1,2,3,3,4,5,6,4,0])
x=np.where(variable==3)
print(x)

(array([2, 3], dtype=int64),)


In [170]:
y=np.where(variable%3==0)
print(y)

(array([2, 3, 6, 8], dtype=int64),)


In [171]:
x1=np.searchsorted(variable,0)

In [172]:
print(x1)

0


In [173]:
x2=np.searchsorted(variable,[9,10,11])

In [174]:
print(x2)

[9 9 9]


In [175]:
print(np.sort(variable))

[0 1 2 3 3 4 4 5 6]


In [176]:
variablealpha=np.array(list('pavk'))
x=np.sort(variablealpha)

In [177]:
print(x)

['a' 'k' 'p' 'v']


In [178]:
f=[True,True,False,False]
n=variablealpha[f]
print(n)

['p' 'a']


In [179]:
np.random.shuffle(variablealpha)
print(variablealpha)

['k' 'a' 'v' 'p']


In [180]:
x=np.unique(variable,return_index=True,return_counts=True)
print(x)

(array([0, 1, 2, 3, 4, 5, 6]), array([8, 0, 1, 2, 4, 5, 6], dtype=int64), array([1, 1, 1, 2, 2, 1, 1], dtype=int64))


In [181]:
r=np.resize(variable,(3,3))

In [182]:
print(r)

[[1 2 3]
 [3 4 5]
 [6 4 0]]


In [183]:
print(r.flatten())

[1 2 3 3 4 5 6 4 0]


In [184]:
print(np.ravel(r))

[1 2 3 3 4 5 6 4 0]


In [185]:
variable=np.insert(variable,2,10)
print(variable)

[ 1  2 10  3  3  4  5  6  4  0]


In [187]:
print(np.insert(var,(2,3),(10,80)))#####doubt

[ 1  3 10 45 80  6]


In [196]:
va=np.matrix([a,b])
va1=va.copy()
print(va+va1)
print(va-va1)
va2=va1.reshape((4,2))
print(va*va2)
print(va2*va)
print(va)


[[  2   6  90  12]
 [  6   8  12 126]]
[[0 0 0 0]
 [0 0 0 0]]
[[ 307  579]
 [ 579 4026]]
[[  10   15   63  195]
 [  63  159 2061  648]
 [  15   25  159  270]
 [ 195  270  648 4005]]
[[ 1  3 45  6]
 [ 3  4  6 63]]


In [197]:
print(np.transpose(va))

[[ 1  3]
 [ 3  4]
 [45  6]
 [ 6 63]]


In [199]:
print(np.swapaxes(va,0,1))

[[ 1  3]
 [ 3  4]
 [45  6]
 [ 6 63]]


In [201]:
vasquare=np.matrix([[1,2],[3,4]])
print(np.linalg.inv(vasquare))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [202]:
print(vasquare)

[[1 2]
 [3 4]]


In [204]:
np.linalg.matrix_power(vasquare,2)

matrix([[ 7, 10],
        [15, 22]])

In [205]:
np.linalg.matrix_power(vasquare,0)

matrix([[1, 0],
        [0, 1]])

In [206]:
np.linalg.matrix_power(vasquare,-3)

matrix([[-14.75 ,   6.75 ],
        [ 10.125,  -4.625]])

In [211]:
print(round(np.linalg.det(vasquare),1))

-2.0


In [2]:
import numpy as np
np.__version__

'1.21.5'

In [6]:
np.tile(np.arange(10),(5,4))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [7]:
np.tile(np.arange(5),(2,2))

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])

In [8]:
np.repeat([1,2],5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [9]:
np.linspace(1,4,5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [10]:
np.matrix('1,2;3,4')

matrix([[1, 2],
        [3, 4]])

In [11]:
a=np.arange(20).reshape(4,5,1)

In [12]:
a

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]]])

In [14]:
ab=np.arange(20).reshape(5,4)

In [16]:
ab

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [17]:
a.shape

(4, 5, 1)

In [18]:
a[1]

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [19]:
a[1,2]

array([7])

In [20]:
a[2]

array([[10],
       [11],
       [12],
       [13],
       [14]])

In [21]:
a[2,1]

array([11])

In [22]:
a=a.squeeze()

In [23]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
a.shape

(4, 5)

In [28]:
x=a[0:3].copy()

In [29]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [30]:
np.pi

3.141592653589793

In [31]:
np.full((3,4),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [32]:
np.full((2,2),2)

array([[2, 2],
       [2, 2]])

In [33]:
np.empty((2,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [6.23047842e-307, 2.22526399e-307, 2.05837348e-312]])

In [34]:
np.arange(1,5,dtype='f')

array([1., 2., 3., 4.], dtype=float32)

In [35]:
np.arange(1,4,dtype='i')

array([1, 2, 3], dtype=int32)

In [36]:
np.arange(1,5,0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75])

In [37]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
a=a.ravel()

In [41]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [42]:
q=np.full((3,4),1.2)

In [43]:
q1=np.full((2,4),1.3)
q2=np.full((2,4),1)

In [44]:
q3=np.vstack((q,q1,q2))

In [45]:
q3

array([[1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2],
       [1.3, 1.3, 1.3, 1.3],
       [1.3, 1.3, 1.3, 1.3],
       [1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 1. ]])

In [47]:
q4=np.hstack((q,q1))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [48]:
q1=np.full((3,4),2)

In [50]:
q4=np.hstack((q,q1))

In [51]:
q4

array([[1.2, 1.2, 1.2, 1.2, 2. , 2. , 2. , 2. ],
       [1.2, 1.2, 1.2, 1.2, 2. , 2. , 2. , 2. ],
       [1.2, 1.2, 1.2, 1.2, 2. , 2. , 2. , 2. ]])

In [52]:
q4.shape

(3, 8)

In [53]:
q4.transpose()

array([[1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2],
       [2. , 2. , 2. ],
       [2. , 2. , 2. ],
       [2. , 2. , 2. ],
       [2. , 2. , 2. ]])

In [54]:
q4[(1,2),2:4]## rows 0 and 2,columns 2 to 4

array([[1.2, 1.2],
       [1.2, 1.2]])

In [55]:
q4[1:3,2:4]

array([[1.2, 1.2],
       [1.2, 1.2]])

In [57]:
b=np.arange(48).reshape(4,12)
b


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [58]:
b[(0,2),2:5]

array([[ 2,  3,  4],
       [26, 27, 28]])

In [59]:
b[:,(-1,2,-1)]

array([[11,  2, 11],
       [23, 14, 23],
       [35, 26, 35],
       [47, 38, 47]])

In [61]:
c=b.reshape(4,2,6)

In [62]:
c

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [64]:
c[1,0,4]# matrix 1,row 0,col4 element

16

In [65]:
c[1,...]#matrix 1 ,all rows,all columns

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [67]:
c[1,1,...]##matrix 1 ,row1,all columns

array([18, 19, 20, 21, 22, 23])

In [69]:
c[1,...,3]#matrix 1 ,all rows,column3

array([15, 21])

In [72]:
c[...,3]#all matrices ,all rows , column 3

array([[ 3,  9],
       [15, 21],
       [27, 33],
       [39, 45]])

In [78]:
for i, m in enumerate(c):
    print('item:',i)
    print(m)
    

item: 0
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
item: 1
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
item: 2
[[24 25 26 27 28 29]
 [30 31 32 33 34 35]]
item: 3
[[36 37 38 39 40 41]
 [42 43 44 45 46 47]]


In [79]:
m=np.arange(9).reshape(3,3)

In [80]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
q,r=np.linalg.qr(m)

In [82]:
q

array([[ 0.        ,  0.91287093,  0.40824829],
       [-0.4472136 ,  0.36514837, -0.81649658],
       [-0.89442719, -0.18257419,  0.40824829]])

In [83]:
r

array([[-6.70820393e+00, -8.04984472e+00, -9.39148551e+00],
       [ 0.00000000e+00,  1.09544512e+00,  2.19089023e+00],
       [ 0.00000000e+00,  0.00000000e+00, -3.65307819e-16]])

In [84]:
q.dot(r)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [85]:
np.linalg.det(m)

0.0

In [87]:
ev,eve=np.linalg.eig(m)

In [88]:
ev

array([ 1.33484692e+01, -1.34846923e+00, -1.26963291e-15])

In [89]:
eve

array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]])