# NumPy: Python library for numerical operations on arrays and matrices. Capabilities include efficient mathematical operations.

Support for mathematical operations and functions that can be applied to entire arrays at once, without the need for loops or iteration.

In [10]:
import numpy as np

# create a 1-dimensional array from a list
arr1d = np.array([1, 2, 3, 4, 5])

# create a 2-dimensional array from a list of lists
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# create a 3-dimensional array from a list of lists of lists
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


Sure, here's an example code that creates an n-dimensional NumPy array based on user input:

In [79]:
import numpy as np

# get user input for array shape
shape_str = input("Enter shape of array (separated by commas): ")
shape = tuple(map(int, shape_str.split(",")))

# create n-dimensional array of zeros with user-defined shape
arr = np.zeros(shape)

print(arr)


Enter shape of array (separated by commas): 3,2
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In a 3D array, the first dimension refers to the outermost layer or the "z-axis". The second dimension refers to the "y-axis", and the third dimension refers to the "x-axis".

To illustrate this, consider a simple 3D array that represents a cube. The shape of the array could be (3, 3, 3), indicating that it has three elements along each of its dimensions. In this case, the first dimension corresponds to the height of the cube, the second dimension corresponds to the width of the cube, and the third dimension corresponds to the depth of the cube.

(x,y) = (1,1) 

(z,y,x) = (0,0,0)

In [168]:
a=np.array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

a.shape

(3, 3, 3)

# ndarray.shape,ndim,size,dtype,astype

In [88]:
n = np.array([[[1,1,1],[2,2,2],[3,3,3]],[[1,1,1],[2,2,2],[3,3,3]]])

In [89]:
n.shape

(2, 3, 3)

In [90]:
n.ndim

3

In [91]:
n.size

18

In [92]:
n.dtype

dtype('int32')

In [93]:
n.astype('float')

array([[[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]],

       [[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]]])

# creating arrays in differnt ways

ndarray.empty,ones,zeros,arange,linspace,random.random,random.randint,full,identity,list,tuple

In [105]:
k = np.empty([2,3],dtype=int)
k

array([[ 1000345280,         327,  1023042736],
       [        327,           0, -2147483648]])

In [114]:
k = np.ones([3,3], dtype=int)
k

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [119]:
k = np.zeros([2,2],dtype=int)
k

array([[0, 0],
       [0, 0]])

In [122]:
k = np.arange(10)
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
k = np.arange(10,100,20, dtype = int)
k

array([10, 30, 50, 70, 90])

In [128]:
k = np.linspace(10,100,10,endpoint=True,
    retstep=True,
    dtype=int,
    axis=0)

k

(array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]), 10.0)

In [185]:
k = np.random.random(((3,3,3)))
k

array([[[0.80374009, 0.35339801, 0.50661438],
        [0.4079187 , 0.97135184, 0.33152037],
        [0.98562897, 0.54181329, 0.46643995]],

       [[0.53350665, 0.32122474, 0.74290703],
        [0.28359541, 0.77001526, 0.93646233],
        [0.2050705 , 0.60313976, 0.15573939]],

       [[0.7582368 , 0.75457086, 0.96104824],
        [0.76777823, 0.79947619, 0.94938457],
        [0.24917811, 0.41935416, 0.59577889]]])

In [142]:
k = np.random.randint(0,10,size=(3,3,3))
k

array([[[7, 4, 4],
        [9, 0, 0],
        [3, 5, 1]],

       [[4, 5, 2],
        [8, 3, 4],
        [4, 2, 1]],

       [[6, 8, 5],
        [6, 8, 4],
        [1, 4, 9]]])

In [149]:
k = np.full((3,3,3),10)
k

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [151]:
k = np.identity(5,dtype=int)
k

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [156]:
k=((1,2,3),(1,1,1))
np.asarray(k)

array([[1, 2, 3],
       [1, 1, 1]])

# indexing and slicing

In [162]:
k = np.random.randint(1,100,size=(1,3,3))
k

array([[[89, 85, 12],
        [50, 85, 37],
        [91, 23, 80]]])

In [160]:
k[0,1,1]

89

In [169]:
k[:,1,:] #(z,x,y) #(: whole)

array([[50, 85, 37]])

# array manipulation

np.transpose,reshape,resize,flatten

In [180]:
k = np.random.randint(1,29,size=(2,3,3))
k.shape

(2, 3, 3)

In [181]:
k.transpose().shape

(3, 3, 2)

In [177]:
k.size

6

In [184]:
k.reshape(1,9,2)

array([[[ 3, 18],
        [ 9, 19],
        [ 1, 14],
        [ 6,  1],
        [22,  5],
        [ 9, 25],
        [ 1, 19],
        [22, 26],
        [ 7, 12]]])

In [197]:
k=np.random.random(((2,3,2)))
k

array([[[0.67531379, 0.49200234],
        [0.69854776, 0.91092252],
        [0.47560582, 0.93234846]],

       [[0.11231955, 0.7085014 ],
        [0.3658782 , 0.41555829],
        [0.49886869, 0.928919  ]]])

In [199]:
np.resize(k,(3,3,3))

array([[[0.67531379, 0.49200234, 0.69854776],
        [0.91092252, 0.47560582, 0.93234846],
        [0.11231955, 0.7085014 , 0.3658782 ]],

       [[0.41555829, 0.49886869, 0.928919  ],
        [0.67531379, 0.49200234, 0.69854776],
        [0.91092252, 0.47560582, 0.93234846]],

       [[0.11231955, 0.7085014 , 0.3658782 ],
        [0.41555829, 0.49886869, 0.928919  ],
        [0.67531379, 0.49200234, 0.69854776]]])

In [200]:
k.flatten()

array([0.67531379, 0.49200234, 0.69854776, 0.91092252, 0.47560582,
       0.93234846, 0.11231955, 0.7085014 , 0.3658782 , 0.41555829,
       0.49886869, 0.928919  ])

# copy and view

In [201]:
k = np.random.randint(1,20,size=(1,2,3))

In [202]:
m= k.copy()

In [212]:
k

array([[[ 2, 13,  5],
        [ 1, 14, 13]]])

In [210]:
m[0,0,0] = 3

In [211]:
m

array([[[ 3, 13,  5],
        [ 1, 14, 13]]])

# insert,append,delete,unique

In [213]:
np.array()

array([[[ 2, 13,  5],
        [ 1, 14, 13]]])

When performing operations on 2D arrays, the axis parameter is used to specify which axis to perform the operation on. For example, if we want to compute the sum of each row in the array, we would set axis=1:   

If we want to compute the sum of each column, we would set axis=0:


axis=0: column

axis=1 : row

In [218]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [219]:
total_sum = np.sum(arr, axis=None)
print(total_sum)  # Output: 21


21


In [222]:
row_sum = np.sum(arr, axis=1)
print(row_sum)  # Output: [ 6 15]


[ 6 15]


In [224]:
row_sum = np.sum(arr, axis=0)
print(row_sum)


[5 7 9]


In [234]:
# Create a new column with 3 elements
new_col = np.array([[[13, 14,12]]])

In [235]:
k

array([[[ 2, 13,  5],
        [ 1, 14, 13]]])

In [236]:
np.insert(k,1,new_col,axis=1)

array([[[ 2, 13,  5],
        [13, 14, 12],
        [ 1, 14, 13]]])

In [238]:
np.insert(k,0,new_col,axis=0)

array([[[13, 14, 12],
        [13, 14, 12]],

       [[ 2, 13,  5],
        [ 1, 14, 13]]])

In [241]:
#EXAMPLE 2

k = np.random.randint(1,100,(3,2,3))
k

array([[[84, 82, 38],
        [13, 16, 99]],

       [[17, 36, 62],
        [12, 91, 20]],

       [[34, 52, 32],
        [20, 96, 57]]])

In [244]:
l=np.random.randint(1,189,(1,2,3))

In [267]:
np.insert(k,3,l,axis=0)

array([[[ 84,  82,  38],
        [ 13,  16,  99]],

       [[ 17,  36,  62],
        [ 12,  91,  20]],

       [[ 34,  52,  32],
        [ 20,  96,  57]],

       [[107, 107, 107],
        [ 68,  68,  68]],

       [[ 73,  73,  73],
        [150, 150, 150]],

       [[ 73,  73,  73],
        [ 32,  32,  32]],

       [[172, 172, 172],
        [149, 149, 149]]])

In [271]:
l=np.random.randint(1,189,(4,1,3))
l

array([[[ 27,  43,  22]],

       [[ 37, 179, 107]],

       [[  6,  56, 110]],

       [[182,  88,   1]]])

In [272]:
np.insert(k,2,l,axis=1)

array([[[ 84,  82,  38],
        [ 13,  16,  99],
        [ 27,  43,  22],
        [ 37, 179, 107],
        [  6,  56, 110],
        [182,  88,   1]],

       [[ 17,  36,  62],
        [ 12,  91,  20],
        [ 27,  43,  22],
        [ 37, 179, 107],
        [  6,  56, 110],
        [182,  88,   1]],

       [[ 34,  52,  32],
        [ 20,  96,  57],
        [ 27,  43,  22],
        [ 37, 179, 107],
        [  6,  56, 110],
        [182,  88,   1]]])

In [275]:
l

array([[[ 27,  43,  22]],

       [[ 37, 179, 107]],

       [[  6,  56, 110]],

       [[182,  88,   1]]])

In [276]:
k = np.random.randint(1,100,(4,1,3))
k

array([[[70, 82, 39]],

       [[49, 98,  2]],

       [[82, 81, 25]],

       [[22, 96, 39]]])

In [277]:
np.append(l,k,axis=1)

array([[[ 27,  43,  22],
        [ 70,  82,  39]],

       [[ 37, 179, 107],
        [ 49,  98,   2]],

       [[  6,  56, 110],
        [ 82,  81,  25]],

       [[182,  88,   1],
        [ 22,  96,  39]]])

In [289]:
np.unique(k, return_index=True,
    return_counts=True,
    axis=None,)

(array([ 2, 22, 25, 39, 49, 70, 81, 82, 96, 98]),
 array([ 5,  9,  8,  2,  3,  0,  7,  1, 10,  4], dtype=int64),
 array([1, 1, 1, 2, 1, 1, 1, 2, 1, 1], dtype=int64))

In [290]:
k

array([[[70, 82, 39]],

       [[49, 98,  2]],

       [[82, 81, 25]],

       [[22, 96, 39]]])

In [291]:
np.delete(k,0,axis=0)

array([[[49, 98,  2]],

       [[82, 81, 25]],

       [[22, 96, 39]]])

# Broadcasting is a powerful feature of NumPy that allows arrays with different shapes to be used in arithmetic operations. The basic idea is that smaller arrays are "broadcast" across the larger arrays so that they have compatible shapes.

In general, broadcasting works when the arrays have the same number of dimensions, and the size of each dimension either matches or is equal to 1. Broadcasting is performed along the dimensions where the sizes differ.

In [296]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

c = a + b


In [297]:
c

array([[2, 4, 6],
       [5, 7, 9]])

In [298]:
a.shape

(2, 3)

In [299]:
b.shape

(3,)

In [300]:
c.shape

(2, 3)

In [301]:
import numpy as np

# create a 2D array with shape (3, 4)
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# create a 1D array with shape (4,)
b = np.array([1, 0, -1, 2])

# create a 2D array with shape (3, 1)
c = np.array([[2], [3], [4]])

# multiply a by b element-wise along the second dimension
d = a * b

# add c to d along the first dimension
e = c + d

print("Array a:")
print(a)

print("Array b:")
print(b)

print("Array c:")
print(c)

print("Array d:")
print(d)

print("Array e:")
print(e)


Array a:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array b:
[ 1  0 -1  2]
Array c:
[[2]
 [3]
 [4]]
Array d:
[[  1   0  -3   8]
 [  5   0  -7  16]
 [  9   0 -11  24]]
Array e:
[[ 3  2 -1 10]
 [ 8  3 -4 19]
 [13  4 -7 28]]


In [302]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [303]:
b

array([ 1,  0, -1,  2])

In [306]:
np.add(a,b)

array([[ 2,  2,  2,  6],
       [ 6,  6,  6, 10],
       [10, 10, 10, 14]])

In [312]:
np.subtract(a,b)

array([[ 0,  2,  4,  2],
       [ 4,  6,  8,  6],
       [ 8, 10, 12, 10]])

In [313]:
np.multiply(a,b)

array([[  1,   0,  -3,   8],
       [  5,   0,  -7,  16],
       [  9,   0, -11,  24]])

In [314]:
np.divide(a,b)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_216\2626738034.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(a,b)


array([[  1.,  inf,  -3.,   2.],
       [  5.,  inf,  -7.,   4.],
       [  9.,  inf, -11.,   6.]])

In [316]:
np.sum(a)

78

In [317]:
np.min(a)

1

In [318]:
np.max(a)

12

In [319]:
np.mean(a)

6.5

In [320]:
np.sort(a)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [340]:
np.ones((3,3),dtype=int) +  np.arange(3)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])